import './globals.css';

import type { Metadata } from 'next';
import { M_PLUS_1p } from 'next/font/google';
import { ReactNode } from 'react';

import Header from '@/components/Header';
import BottomNav from '@/components/BottomNav';
import Footer from '@/components/Footer';

const mPlus1p = M_PLUS_1p({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
  adjustFontFallback: false,
  variable: '--font-mplus1p',
});

export const metadata: Metadata = {
  title: 'チャレンジAIクイズ',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ja-JP">
      <body className={`${mPlus1p.variable} font-sans`}>
        <Header />
        <main className="mx-auto mb-auto mt-6 w-screen max-w-4xl px-4 sm:mt-24 lg:px-0">
          {children}
        </main>
        <Footer />
        <BottomNav />
      </body>
    </html>
  );
}
